/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Aliases kept for parity with the TypeScript `audio-metadata` package.
 * `AudioSpecs` is the single flat shape every parse call returns; the
 * `kind` field narrows it.
 */
export type AudioMeta = AudioSpecs
export type ExpandedAudioSpecs = AudioSpecs
export type Mp3Meta = AudioSpecs & { kind: 'mp3'; format: 'mp3'; ext: 'mp3'; mime: 'audio/mpeg' }
export type WavMeta = AudioSpecs & { kind: 'wav'; format: 'wav'; ext: 'wav'; mime: 'audio/wav' }

/** The WASI flavor this loader instantiates. */
export declare const __napiBindingTarget: 'wasm32-wasi'

/**
 * One audio buffer, copied exactly once into shared memory. Sync methods
 * borrow it; async methods share it with the worker through `Arc`.
 */
export declare class AudioDown {
  constructor(data: Uint8Array, source?: string | undefined | null)
  get kind(): AudioKind
  get byteSize(): number
  get source(): string | null
  metadata(): AudioSpecs
  metadataAsync(): Promise<AudioSpecs>
  decode(options?: DecodeOptions | undefined | null): DecodedAudio
  decodeAsync(options?: DecodeOptions | undefined | null): Promise<DecodedAudio>
  waveform(options?: WaveformOptions | undefined | null): WaveformPeaks
  waveformAsync(options?: WaveformOptions | undefined | null): Promise<WaveformPeaks>
  analyze(options?: WaveformOptions | undefined | null): AudioAnalysis
  analyzeAsync(options?: WaveformOptions | undefined | null): Promise<AudioAnalysis>
  /**
   * Decode once into an `AudioPcm` handle, then reduce it at any number of
   * resolutions without the PCM ever crossing into JS.
   */
  pcm(options?: DecodeOptions | undefined | null): AudioPcm
  pcmAsync(options?: DecodeOptions | undefined | null): Promise<AudioPcm>
}

/**
 * Interleaved `f32` PCM held in shared Rust memory. Build one from
 * `AudioDown.pcm()` / `pcmAsync()` or from your own `Float32Array`.
 */
export declare class AudioPcm {
  constructor(samples: Float32Array, sampleRate: number, channels: number, defaults?: WaveformOptions | undefined | null)
  get sampleRate(): number
  get channels(): number
  /** Frames per channel. */
  get frameCount(): number
  get durationSec(): number
  get gaplessEnabled(): boolean
  get skippedPackets(): number
  /** Copy of the interleaved samples. */
  samples(): Float32Array
  /** The same data as a `DecodedAudio` object (copies the samples). */
  decoded(): DecodedAudio
  waveform(options?: WaveformOptions | undefined | null): WaveformPeaks
  waveformAsync(options?: WaveformOptions | undefined | null): Promise<WaveformPeaks>
}

/**
 * Stateless service. Construct once, call many; every method is also
 * available as a standalone function. Optional constructor defaults are
 * merged under per-call options.
 */
export declare class AudioService {
  constructor(defaults?: WaveformOptions | undefined | null)
  get defaults(): WaveformOptions
  sniffAudio(data: Uint8Array): AudioKind | null
  parseAudio(data: Uint8Array, source?: string | undefined | null): AudioSpecs
  parseAudioAsync(data: Uint8Array, source?: string | undefined | null): Promise<AudioSpecs>
  parseMp3(data: Uint8Array, source?: string | undefined | null): Mp3Meta
  parseMp3Async(data: Uint8Array, source?: string | undefined | null): Promise<Mp3Meta>
  parseWav(data: Uint8Array, source?: string | undefined | null): WavMeta
  parseWavAsync(data: Uint8Array, source?: string | undefined | null): Promise<WavMeta>
  decodeAudio(data: Uint8Array, options?: DecodeOptions | undefined | null): DecodedAudio
  decodeAudioAsync(data: Uint8Array, options?: DecodeOptions | undefined | null): Promise<DecodedAudio>
  waveformPeaks(data: Uint8Array, options?: WaveformOptions | undefined | null): WaveformPeaks
  waveformPeaksAsync(data: Uint8Array, options?: WaveformOptions | undefined | null): Promise<WaveformPeaks>
  waveformFromPcm(samples: Float32Array, sampleRate: number, channels: number, options?: WaveformOptions | undefined | null): WaveformPeaks
  waveformFromPcmAsync(samples: Float32Array, sampleRate: number, channels: number, options?: WaveformOptions | undefined | null): Promise<WaveformPeaks>
  analyzeAudio(data: Uint8Array, options?: WaveformOptions | undefined | null, source?: string | undefined | null): AudioAnalysis
  analyzeAudioAsync(data: Uint8Array, options?: WaveformOptions | undefined | null, source?: string | undefined | null): Promise<AudioAnalysis>
  /**
   * Snapshot a buffer once and reuse it across metadata, decode, waveform
   * and analyze calls. Inherits this service's defaults.
   */
  open(data: Uint8Array, source?: string | undefined | null): AudioDown
}

export declare function analyzeAudio(data: Uint8Array, options?: WaveformOptions | undefined | null, source?: string | undefined | null): AudioAnalysis

export declare function analyzeAudioAsync(data: Uint8Array, options?: WaveformOptions | undefined | null, source?: string | undefined | null): Promise<AudioAnalysis>

export interface AudioAnalysis {
  specs: AudioSpecs
  waveform: WaveformPeaks
}

export type AudioContainer = 'mpeg' | 'RIFF' | 'RF64'

export type AudioKind = 'mp3' | 'wav'

/**
 * Flat, nullable audio specs shaped like `ImageSpecs` / `ExpandedImgSpecs`
 * from `@d0paminedriven/fs`, with the Prisma `AudioMetadata` columns and the
 * ws-server `mp3Specs` fields folded in so the same object feeds all three.
 */
export interface AudioSpecs {
  type: 'AUDIO'
  /** Discriminant for narrowing; equals `format` and `ext`. */
  kind: AudioKind
  /** `ImageSpecs.format` analogue. */
  format: AudioKind
  ext: AudioKind
  mime: 'audio/mpeg' | 'audio/wav'
  /** `DocSpecs.mimeType` analogue; same value as `mime`. */
  mimeType: 'audio/mpeg' | 'audio/wav'
  /** `Expanded*Specs.contentType` analogue; same value as `mime`. */
  contentType: 'audio/mpeg' | 'audio/wav'
  /**
   * `mp3` / `mp2` / `mp1` by MPEG layer; WAVE format name otherwise, with
   * WAVE_FORMAT_EXTENSIBLE resolved through its SubFormat GUID.
   */
  codec: 'mp3' | 'mp2' | 'mp1' | 'pcm' | 'ieee-float' | 'alaw' | 'mulaw' | 'extensible' | 'unknown' | `tag:${number}`
  container: AudioContainer
  /** Length of the parsed buffer in bytes (`Expanded*Specs.byteSize`). */
  byteSize: number
  /** Same as `byteSize`: the bytes this parse actually saw. */
  fetchedBytes: number
  /** Same as `byteSize` (`mp3Specs.size`). */
  size: number
  /** Passed through from the caller, e.g. a CDN URL. */
  source?: string
  durationSec: number | null
  /** Rounded milliseconds (Prisma `AudioMetadata.duration`). */
  durationMs: number | null
  durationSource: DurationSource | null
  sampleRate: number | null
  channels: number | null
  /** Average bits per second across the whole stream (`mp3Specs.bitrate`). */
  bitrate: number | null
  /** Nominal kilobits per second of the first frame (MP3) or the byte rate (WAVE). */
  bitrateKbps: number | null
  /** WAVE only. */
  bitsPerSample: number | null
  cbr: boolean | null
  vbr: boolean | null
  /** MP3: MPEG frames walked. WAVE: `null`. */
  frames: number | null
  /** PCM frames per channel known from headers without decoding. */
  sampleFrames: number | null
  /** MP3: gaps between frames that were skipped. WAVE: `null`. */
  resyncs: number | null
  /** MP3: the last frame runs past the buffer (prefix probe). WAVE: `null`. */
  truncated: boolean | null
  title: string | null
  artist: string | null
  album: string | null
  genre: string | null
  /** Four-digit year parsed from the ID3 year/date or WAVE ICRD tag. */
  year: number | null
  tags: AudioTags
  /** `ImageSpecs.metadata`-style record of every present tag. */
  metadata?: Record<string, string>
  id3v2: Id3v2Entity | null
  /** First validated MPEG frame. */
  frame: MpegFrame | null
  xing: XingHeader | null
  /** Byte offset where audio starts: after ID3v2 for MP3, the `data` body for WAVE. */
  audioOffset: number | null
  formatTag: number | null
  byteRate: number | null
  blockAlign: number | null
  dataOffset: number | null
  /** Bytes of the `data` chunk present in the buffer (a prefix underestimates). */
  dataSize: number | null
}

/**
 * Every tag either container can carry. MP3 fills the ID3 subset, WAVE fills
 * the LIST/INFO subset; absent tags are omitted.
 */
export interface AudioTags {
  title?: string
  artist?: string
  album?: string
  track?: string
  genre?: string
  comment?: string
  /** Raw ID3 TYER/TDRC text, e.g. `"2024"` or `"2024-05-01T12:00:00"`. */
  year?: string
  /** Raw WAVE ICRD text. */
  date?: string
  software?: string
  copyright?: string
  engineer?: string
  subject?: string
}

export declare function decodeAudio(data: Uint8Array, options?: DecodeOptions | undefined | null): DecodedAudio

export declare function decodeAudioAsync(data: Uint8Array, options?: DecodeOptions | undefined | null): Promise<DecodedAudio>

export interface DecodedAudio {
  /** Interleaved frames: `L0 R0 L1 R1 ...` for stereo. */
  samples: Float32Array
  sampleRate: number
  channels: number
  /** Frames per channel, not total scalar samples. */
  frameCount: number
  durationSec: number
  gaplessEnabled: boolean
  skippedPackets: number
}

export interface DecodeOptions {
  /** Trim encoder delay/padding when gapless metadata is present. Default `true`. */
  gapless?: boolean
  /** Fail on the first decoder error instead of skipping the packet. Default `true`. */
  strict?: boolean
  /** Cap on interleaved scalar samples kept in memory. Default `64_000_000`. */
  maxDecodedSamples?: number
}

export type DurationSource = 'frames' | 'xing' | 'fact' | 'data'

export interface Id3v2Entity {
  version: `2.${2 | 3 | 4}.${number}`
  /** Total tag size in bytes, including header and footer. */
  size: number
}

export type MpegChannelMode = 'stereo' | 'joint-stereo' | 'dual-channel' | 'mono'

export interface MpegFrame {
  /** Byte offset of the frame header within the buffer. */
  offset: number
  version: MpegVersion
  layer: MpegLayer
  bitrateKbps: number
  sampleRate: number
  channels: 1 | 2
  channelMode: MpegChannelMode
  padding: boolean
  hasCrc: boolean
  samplesPerFrame: 384 | 576 | 1152
  frameSize: number
}

export type MpegLayer = 'I' | 'II' | 'III'

export type MpegVersion = '1' | '2' | '2.5'

export declare function parseAudio(data: Uint8Array, source?: string | undefined | null): AudioSpecs

export declare function parseAudioAsync(data: Uint8Array, source?: string | undefined | null): Promise<AudioSpecs>

export declare function parseMp3(data: Uint8Array, source?: string | undefined | null): Mp3Meta

export declare function parseMp3Async(data: Uint8Array, source?: string | undefined | null): Promise<Mp3Meta>

export declare function parseWav(data: Uint8Array, source?: string | undefined | null): WavMeta

export declare function parseWavAsync(data: Uint8Array, source?: string | undefined | null): Promise<WavMeta>

/** Cheap magic sniff: `'mp3'`, `'wav'` or `null`. */
export declare function sniffAudio(data: Uint8Array): AudioKind | null

export interface WaveformChannel {
  /** Signed minimum per bucket. */
  min: Float32Array
  /** Signed maximum per bucket. */
  max: Float32Array
  /** `max(|min|, |max|)` per bucket. */
  peak: Float32Array
  /** `sqrt(sum(sample²) / frames)` per bucket, accumulated in f64. */
  rms: Float64Array
}

export declare function waveformFromPcm(samples: Float32Array, sampleRate: number, channels: number, options?: WaveformOptions | undefined | null): WaveformPeaks

export declare function waveformFromPcmAsync(samples: Float32Array, sampleRate: number, channels: number, options?: WaveformOptions | undefined | null): Promise<WaveformPeaks>

export interface WaveformOptions {
  /** Target bucket count (capped at the frame count). Default `1024`. Exclusive with `samplesPerPeak`. */
  peakCount?: number
  /** Fixed frames per bucket. Exclusive with `peakCount`. */
  samplesPerPeak?: number
  /** Reduce buckets on the rayon pool for large inputs. Default `true`. */
  parallel?: boolean
  gapless?: boolean
  strict?: boolean
  maxDecodedSamples?: number
}

export declare function waveformPeaks(data: Uint8Array, options?: WaveformOptions | undefined | null): WaveformPeaks

export interface WaveformPeaks {
  sampleRate: number
  channelCount: number
  /** Frames per channel. */
  frameCount: number
  /** Decoded duration: `frameCount / sampleRate`. */
  durationSec: number
  /** Actual bucket count (`peakCount` is capped at `frameCount`). */
  peakCount: number
  /** `peakCount + 1` frame offsets; bucket `i` covers `[boundaries[i], boundaries[i + 1])`. */
  boundaries: Uint32Array
  channels: Array<WaveformChannel>
  /**
   * `max(channel.peak[i])` across channels: the single-line display envelope.
   * `Array.from(envelope)` is what a `waveformPeaks` column wants.
   */
  envelope: Float32Array
  gaplessEnabled: boolean
  skippedPackets: number
}

export declare function waveformPeaksAsync(data: Uint8Array, options?: WaveformOptions | undefined | null): Promise<WaveformPeaks>

export interface XingHeader {
  kind: XingKind
  frames: number | null
  bytes: number | null
}

export type XingKind = 'Xing' | 'Info'
